[package]
name = "lla_plugin_interface"
description = "Interface for lla plugins"
version = "0.1.1"
edition = "2021"
authors = ["Achaq <hi@achaq.dev>"]
license = "MIT"
repository = "https://github.com/triyanox/lla"
keywords = ["cli", "ls", "lightweight"]
categories = ["command-line-utilities"]
exclude = ["lla.png"]


[dependencies]
